changed python version in msprime env
Changed from `python=3` to `python=3.6` because of version issues. 

This fixes the following error:
```
RuntimeError: the sip module implements API v12.0 to v12.4 but the PyQt5.QtCore module requires API v12.5
```